FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
    Velocity_flat:
      id: 4
      type: RLBase
    Velocity_crouch:
      id: 5
      type: RLBase
  Passive:
    transitions: 
      FixStand: A.on_pressed
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: start.on_pressed
      Velocity_flat: X.on_pressed
      Velocity_crouch: Y.on_pressed
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5],
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity_flat: X.on_pressed
      Velocity_crouch: Y.on_pressed
    policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-06-23_13-23-53 #go2 爬樓梯
    #policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-06-02_10-05-49 #go2 爬樓梯
  Velocity_flat:
    transitions:
      Passive: LT +B.on_pressed
      Velocity: start.on_pressed
      Velocity_crouch: Y.on_pressed
    #policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-02-03_15-54-17 #平地
    policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-06-24_11-48-09 #平地(any terrain)
  Velocity_crouch:
    transitions:
      Passive: LT +B.on_pressed
      Velocity: start.on_pressed
      Velocity_flat: X.on_pressed
    #policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-02-11_19-01-34 #匍匐
    policy_dir: ../../../logs/rsl_rl/unitree_go2_velocity/2026-05-26_20-17-49 #匍匐(any terrain)
    
    
